// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsOnKn7KOR0YYTdreQS4wntpejGTAN_ZI',
    appId: '1:702604567596:web:5d36478f1357b814ae1d89',
    messagingSenderId: '702604567596',
    projectId: 'uni-scanner-3b8b2',
    authDomain: 'uni-scanner-3b8b2.firebaseapp.com',
    storageBucket: 'uni-scanner-3b8b2.firebasestorage.app',
    measurementId: 'G-0K005E6K0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8CgI8B6b7R4DVgB7-NiKQ8WL20_OI6Aw',
    appId: '1:702604567596:android:750b48588f0a442dae1d89',
    messagingSenderId: '702604567596',
    projectId: 'uni-scanner-3b8b2',
    storageBucket: 'uni-scanner-3b8b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-edf9ywJhvbZQ-5PVqtg7JNca_82hALU',
    appId: '1:702604567596:ios:01fcc36be3edc366ae1d89',
    messagingSenderId: '702604567596',
    projectId: 'uni-scanner-3b8b2',
    storageBucket: 'uni-scanner-3b8b2.firebasestorage.app',
    iosBundleId: 'com.example.uniScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-edf9ywJhvbZQ-5PVqtg7JNca_82hALU',
    appId: '1:702604567596:ios:01fcc36be3edc366ae1d89',
    messagingSenderId: '702604567596',
    projectId: 'uni-scanner-3b8b2',
    storageBucket: 'uni-scanner-3b8b2.firebasestorage.app',
    iosBundleId: 'com.example.uniScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsOnKn7KOR0YYTdreQS4wntpejGTAN_ZI',
    appId: '1:702604567596:web:1837cb965b3d43b5ae1d89',
    messagingSenderId: '702604567596',
    projectId: 'uni-scanner-3b8b2',
    authDomain: 'uni-scanner-3b8b2.firebaseapp.com',
    storageBucket: 'uni-scanner-3b8b2.firebasestorage.app',
    measurementId: 'G-Y9HKKTZTG6',
  );
}
